env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:react/jsx-runtime
overrides: 
  - files: 
    - "**/*.stories.*"
    rules:
      import/no-anonymous-default-export: 'off'
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
settings:
  react:
    version: "18.2"
plugins:
  - react
  - "@typescript-eslint"
ignorePatterns:
  - build
  - "!.storybook"
