extends:
  - stylelint-config-standard
plugins:
  - stylelint-color-format
customSyntax: postcss-sass
rules:
  declaration-block-trailing-semicolon:
    - never
  block-opening-brace-space-before:
    - null
  block-closing-brace-newline-before:
    - null
  color-hex-length:
    - null
  color-hex-case:
    - null
  color-format/format:
    format: "rgb"
