name: build and test
on: [push]
env:
  REACT_APP_GOOGLE_API_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_API_CLIENT_ID }}
  REACT_APP_TODO_BACKEND_HOST: ${{ secrets.REACT_APP_TODO_BACKEND_HOST }}
  REACT_APP_TODO_BACKEND_PORT: ${{ secrets.REACT_APP_TODO_BACKEND_PORT }}
  REACT_APP_DEFAULT_LOCALE: ${{ secrets.REACT_APP_DEFAULT_LOCALE }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12.13.0
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build --if-present
      - name: run tests (with coverage)
        run: npm run test:coverage
      - name: codacy coverage report
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
